name: Build and Deploy Pipeline

on:
  push:
    branches:
      - dockerstage

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Build and Push Docker Image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "${VERSION}"
          docker build -t kupidun/java-app:${VERSION} --build-arg VERSION=${VERSION} .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker image tag kupidun/java-app:$VERSION kupidun/java-app:latest
          docker image tag kupidun/java-app:$VERSION kupidun/java-app:$VERSION
          docker image push kupidun/java-app:$VERSION
          docker image push kupidun/java-app:latest
        working-directory: ./myapp
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}


      - name: Increment Patch Version and Commit
        run: |
          chmod +x versionScript.sh
          ./versionScript.sh
          echo "NEW_VERSION=$(./versionScript.sh)"
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add pom.xml
          git commit -m "Bump version [skip ci]"
          git push
        working-directory: ./myapp
        if: github.ref == 'refs/heads/dockerstage'



      - name: Run Docker Container for Testing
        run: |
          docker pull kupidun/java-app:latest
          CONTAINER_ID=$(docker run --name test_container -d -p 8080:8080 kupidun/java-app:latest)
          sleep 10 # Give some time for the application to start
          docker logs $CONTAINER_ID
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
